

const ActionTypes =  {
    REQUEST_PENDING: 'REQUEST_PENDING',
    REQUEST_SUCCESS: 'REQUEST_SUCCESS',
    REQUEST_FAILED: 'REQUEST_FAILED',
    CLEAR_REQUEST_RESPONSE: 'CLEAR_REQUEST_RESPONSE',
    LOGIN : 'LOGIN',
    LOGIN_CUSTOMER : 'LOGIN_CUSTOMER',
    TRANSACTION : 'TRANSACTION',
    GET_HOT_PRODUCT : 'GET_HOT_PRODUCT',
    SAVE_USER_DATA: 'SAVE_USER_DATA',
    CLEAR_USER_DATA: 'CLEAR_USER_DATA',
};

export default ActionTypes